### ISSUE TITLE
Mobile App: Profile Settings > It doesn't return correct default avatar after being removed

### ISSUE THREAD

**Issue by trucnguyen31** [mezonai/mezon-js#240]
## AR:

![Image](https://github.com/user-attachments/assets/3e70a005-159b-4f0f-85e0-c7d87b7b1316)

![Image](https://github.com/user-attachments/assets/9d09f51c-6790-48e8-aafb-2418799ae6cd)

**Comment by phuocnguyenncc** [comment]
@loi-huynhphuc 
em check lai cai này xem work chưa nhé
